### ISSUE TITLE
Init from JSON

### ISSUE THREAD

**Issue by HarbingerOfFire** [BivittatusDB/BivittatusDB#34]
***Idea***
My idea is to be able to make a new database from a json file. the file will hold some of the basic data about the database. Essentially, it will act as an outline or schema that the database can turn into the normal execution to automatically create a table. 

for an example, a json file made like this:
```json
{
    "test": {
        "table1": {
            "columns": ["id", "name"],
            "data_types":["int", "str"],
            "primary_key": "id"
        }
    }
}
```
Would evaluate to this:
```python
try: bdb.drop("test")
except: pass

test_db=bdb.database("test").init()

tb2=test_db.New_table("table1", 
                       ("id", "name"), 
                       (int, str), 
                       "id")
```

I've tested it like this and it works, but I'm going to work on a more stable implementation:
```
import BivittatusDB as bdb, json

def init_from_json(json_path: str):
    data=dict(json.load(open(json_path)))
    dbname=list(data.keys())[0]
    db=bdb.database(dbname).init()
    tables=data[dbname]
    for table in tables.keys():
        tbname, table=table, tables[table]
        db.New_table(tbname,
                     tuple(table["columns"]),
                     tuple([eval(type) for type in table["data_types"]]),
                     table["primary_key"])
    return db

init_from_json("test.json")
```

DBED: [0004](https://github.com/BivittatusDB/BivittatusDB/wiki/dbed-0004)

**Comment by ScriptSlayer0** [comment]
I think it's a great idea, the next thing I had in mind is that a user can manually enter the columns he/she wants and then enter the type of data he/she wants.
It will take time but I hope it won't give me too many problems.

**Comment by HarbingerOfFire** [comment]
Sounds good. I look forward to your work on it!

**Comment by HarbingerOfFire** [comment]
I like it, I think the only change I would make is allow a blank entry for primary and foreign keys to say that the table doesn't contain one of those keys.

**Comment by HarbingerOfFire** [comment]
Did that makes sense? I'm double guessing my wording right now

**Comment by ScriptSlayer0** [comment]
This makes sense if you are starting to create your first tables without thinking about the DB design (it can also be in case you need to modify the current design).
I will create a separate module to modify JSON files if the user needs it.

**Comment by HarbingerOfFire** [comment]
Sounds good 👍

**Comment by HarbingerOfFire** [comment]
Were you going to make a pull request or make an edit for the changes?

**Comment by HarbingerOfFire** [comment]
Completed with PR #35
